version: '3'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge